[platformio]
src_dir = .
include_dir = .
default_envs = teensy40

[env]
platform = teensy
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF
lib_deps =
  adafruit/Adafruit BNO055
  adafruit/Adafruit Unified Sensor
  pololu/VL53L0X
  pololu/VL53L1X
  sparkfun/SX1509 IO Expander

[env:teensy40]
board = teensy40

[env:teensy41]
board = teensy41
